import type { CatalogModel } from "./catalog";

/**
 * A snapshot of OpenRouter's tool-capable catalog, bundled so the models page has something
 * to show on a first launch with no network and no API key. Refreshed on disk by the first
 * successful fetch; regenerate with `npm run seed:catalog`.
 */
export const catalogSeed: CatalogModel[] = [
  {"id":"deepseek/deepseek-v4-flash-0731","name":"DeepSeek: DeepSeek V4 Flash 0731","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"tencent/hy3","name":"Tencent: Hy3","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"xiaomi/mimo-v2.5","name":"Xiaomi: MiMo-V2.5","contextLength":1048576,"inputModalities":["audio","image"],"free":false},
  {"id":"openai/gpt-5.6-luna","name":"OpenAI: GPT-5.6 Luna","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"deepseek/deepseek-v4-flash","name":"DeepSeek: DeepSeek V4 Flash 0423","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"z-ai/glm-5.2","name":"Z.ai: GLM 5.2","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"nvidia/nemotron-3-ultra-550b-a55b:free","name":"NVIDIA: Nemotron 3 Ultra (free)","contextLength":1000000,"inputModalities":[],"free":true},
  {"id":"anthropic/claude-opus-5","name":"Claude Opus 5","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"deepseek/deepseek-v4-pro","name":"DeepSeek: DeepSeek V4 Pro 0423","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"google/gemini-3.6-flash","name":"Google: Gemini 3.6 Flash","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"minimax/minimax-m3","name":"MiniMax: MiniMax M3","contextLength":1048576,"inputModalities":["image"],"free":false},
  {"id":"poolside/laguna-s-2.1:free","name":"Poolside: Laguna S 2.1 (free)","contextLength":1048576,"inputModalities":[],"free":true},
  {"id":"google/gemini-3.7-flash","name":"Google: Gemini 3.7 Flash","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"moonshotai/kimi-k3","name":"MoonshotAI: Kimi K3","contextLength":1048576,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.6-sol","name":"OpenAI: GPT-5.6 Sol","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"deepseek/deepseek-v4-pro-0813","name":"DeepSeek: DeepSeek V4 Pro 0813","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-sonnet-5","name":"Anthropic: Claude Sonnet 5","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"nvidia/nemotron-3.5-lightning:free","name":"NVIDIA: Nemotron 3.5 Lightning (free)","contextLength":1000000,"inputModalities":[],"free":true},
  {"id":"stealth/ox-alpha","name":"Ox Alpha","contextLength":1048576,"inputModalities":["image"],"free":true},
  {"id":"openai/gpt-5.6-terra","name":"OpenAI: GPT-5.6 Terra","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"google/gemini-3-flash-preview","name":"Google: Gemini 3 Flash Preview","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"google/gemini-2.5-flash-lite","name":"Google: Gemini 2.5 Flash Lite","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"anthropic/claude-sonnet-4.6","name":"Anthropic: Claude Sonnet 4.6","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"stepfun/step-3.7-flash","name":"StepFun: Step 3.7 Flash","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"anthropic/claude-opus-4.7","name":"Anthropic: Claude Opus 4.7","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"xiaomi/mimo-v2.5-pro","name":"Xiaomi: MiMo-V2.5-Pro","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.6-luna-pro","name":"OpenAI: GPT-5.6 Luna Pro","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"upstage/solar-pro4","name":"Upstage: Solar Pro 4","contextLength":524288,"inputModalities":[],"free":false},
  {"id":"x-ai/grok-4.6","name":"SpaceXAI: Grok 4.6","contextLength":500000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-oss-120b","name":"OpenAI: gpt-oss-120b","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"google/gemini-2.5-flash","name":"Google: Gemini 2.5 Flash","contextLength":1048576,"inputModalities":["file","image","audio"],"free":false},
  {"id":"anthropic/claude-opus-4.8","name":"Anthropic: Claude Opus 4.8","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"google/gemini-3.1-flash-lite","name":"Google: Gemini 3.1 Flash Lite","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"deepseek/deepseek-v3.2","name":"DeepSeek: DeepSeek V3.2","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"nvidia/nemotron-3-super-120b-a12b:free","name":"NVIDIA: Nemotron 3 Super (free)","contextLength":1000000,"inputModalities":[],"free":true},
  {"id":"google/gemma-4-31b-it","name":"Google: Gemma 4 31B","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"google/gemma-4-26b-a4b-it","name":"Google: Gemma 4 26B A4B ","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.5","name":"OpenAI: GPT-5.5","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"qwen/qwen3.8-max","name":"Qwen: Qwen3.8 Max","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"anthropic/claude-fable-5","name":"Anthropic: Claude Fable 5","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"google/gemini-3.1-pro-preview","name":"Google: Gemini 3.1 Pro Preview","contextLength":1048576,"inputModalities":["audio","file","image"],"free":false},
  {"id":"anthropic/claude-haiku-4.5","name":"Anthropic: Claude Haiku 4.5","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"z-ai/glm-5.3","name":"Z.ai: GLM 5.3","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4o-mini","name":"OpenAI: GPT-4o-mini","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"cohere/north-mini-code:free","name":"Cohere: North Mini Code (free)","contextLength":256000,"inputModalities":[],"free":true},
  {"id":"minimax/minimax-m2.7","name":"MiniMax: MiniMax M2.7","contextLength":204800,"inputModalities":[],"free":false},
  {"id":"mistralai/mistral-nemo","name":"Mistral: Mistral Nemo","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-opus-4.6","name":"Anthropic: Claude Opus 4.6","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.4","name":"OpenAI: GPT-5.4","contextLength":1050000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3.7-flash","name":"Qwen: Qwen3.7 Flash","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5-mini","name":"OpenAI: GPT-5 Mini","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"x-ai/grok-4.5","name":"SpaceXAI: Grok 4.5","contextLength":500000,"inputModalities":["image","file"],"free":false},
  {"id":"google/gemini-3.5-flash","name":"Google: Gemini 3.5 Flash","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"moonshotai/kimi-k2.6","name":"MoonshotAI: Kimi K2.6","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"poolside/laguna-xs-2.1:free","name":"Poolside: Laguna XS 2.1 (free)","contextLength":262144,"inputModalities":[],"free":true},
  {"id":"google/gemini-3.5-flash-lite","name":"Google: Gemini 3.5 Flash Lite","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"openai/gpt-oss-20b","name":"OpenAI: gpt-oss-20b","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"inclusionai/ling-2.6-flash","name":"inclusionAI: Ling-2.6-flash","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.4-nano","name":"OpenAI: GPT-5.4 Nano","contextLength":400000,"inputModalities":["file","image"],"free":false},
  {"id":"qwen/qwen3.7-max","name":"Qwen: Qwen3.7 Max","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.6-35b-a3b","name":"Qwen: Qwen3.6 35B A3B","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.4-mini","name":"OpenAI: GPT-5.4 Mini","contextLength":400000,"inputModalities":["file","image"],"free":false},
  {"id":"qwen/qwen3.8-27b","name":"Qwen: Qwen3.8 27B","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"google/gemini-3.1-flash-lite-preview","name":"Google: Gemini 3.1 Flash Lite Preview","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"dots-studio/dots-3-note-preview:free","name":"Dots Studio: Dots3-Note Preview (free)","contextLength":512000,"inputModalities":["image"],"free":true},
  {"id":"moonshotai/kimi-k2.7-code","name":"MoonshotAI: Kimi K2.7 Code","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3.7-plus","name":"Qwen: Qwen3.7 Plus","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"meta/muse-spark-1.2","name":"Meta: Muse Spark 1.2","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"inclusionai/ling-3.0-flash","name":"Ling-3.0-flash","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"moonshotai/kimi-k2.5","name":"MoonshotAI: Kimi K2.5","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"anthropic/claude-sonnet-4.5","name":"Anthropic: Claude Sonnet 4.5","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-4.1-mini","name":"OpenAI: GPT-4.1 Mini","contextLength":1047576,"inputModalities":["image","file"],"free":false},
  {"id":"nvidia/nemotron-3.5-lightning","name":"NVIDIA: Nemotron 3.5 Lightning","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-235b-a22b-2507","name":"Qwen: Qwen3 235B A22B Instruct 2507","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"z-ai/glm-5.1","name":"Z.ai: GLM 5.1","contextLength":202752,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.6-sol-pro","name":"OpenAI: GPT-5.6 Sol Pro","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"amazon/nova-micro-v1","name":"Amazon: Nova Micro 1.0","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"meta-llama/llama-3.1-8b-instruct","name":"Meta: Llama 3.1 8B Instruct","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"x-ai/grok-4.3","name":"SpaceXAI: Grok 4.3","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"nex-agi/nex-n2-mini","name":"Nex AGI: Nex-N2-Mini","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"z-ai/glm-4.7","name":"Z.ai: GLM 4.7","contextLength":200000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4.1","name":"OpenAI: GPT-4.1","contextLength":1047576,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3.5-flash-02-23","name":"Qwen: Qwen3.5-Flash","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"poolside/laguna-s-2.1","name":"Poolside: Laguna S 2.1","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"google/gemini-2.5-pro","name":"Google: Gemini 2.5 Pro","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"google/gemma-3-27b-it","name":"Google: Gemma 3 27B","contextLength":131072,"inputModalities":["image"],"free":false},
  {"id":"z-ai/glm-5","name":"Z.ai: GLM 5","contextLength":202752,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.8-2.4t-a95b","name":"Qwen: Qwen3.8 2.4T A95B","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"deepseek/deepseek-chat-v3.1","name":"DeepSeek: DeepSeek V3.1","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5-nano","name":"OpenAI: GPT-5 Nano","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"minimax/minimax-m2.5","name":"MiniMax: MiniMax M2.5","contextLength":204800,"inputModalities":[],"free":false},
  {"id":"nvidia/nemotron-3-nano-30b-a3b:free","name":"NVIDIA: Nemotron 3 Nano 30B A3B (free)","contextLength":256000,"inputModalities":[],"free":true},
  {"id":"nvidia/nemotron-3-ultra-550b-a55b","name":"NVIDIA: Nemotron 3 Ultra","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.5-397b-a17b","name":"Qwen: Qwen3.5 397B A17B","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.6-terra-pro","name":"OpenAI: GPT-5.6 Terra Pro","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-5.3-codex","name":"OpenAI: GPT-5.3-Codex","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-4.1-nano","name":"OpenAI: GPT-4.1 Nano","contextLength":1047576,"inputModalities":["image","file"],"free":false},
  {"id":"meta/muse-spark-1.1","name":"Meta: Muse Spark 1.1","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"meta-llama/llama-3.3-70b-instruct","name":"Meta: Llama 3.3 70B Instruct","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-32b","name":"Qwen: Qwen3 32B","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"x-ai/grok-4.20","name":"SpaceXAI: Grok 4.20","contextLength":2000000,"inputModalities":["image","file"],"free":false},
  {"id":"deepseek/deepseek-chat-v3-0324","name":"DeepSeek: DeepSeek V3 0324","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"google/gemma-3-12b-it","name":"Google: Gemma 3 12B","contextLength":131072,"inputModalities":["image"],"free":false},
  {"id":"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free","name":"NVIDIA: Nemotron 3 Nano Omni (free)","contextLength":256000,"inputModalities":["audio","image"],"free":true},
  {"id":"qwen/qwen3-30b-a3b-instruct-2507","name":"Qwen: Qwen3 30B A3B Instruct 2507","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-vl-32b-instruct","name":"Qwen: Qwen3 VL 32B Instruct","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"z-ai/glm-5v-turbo","name":"Z.ai: GLM 5V Turbo","contextLength":202752,"inputModalities":["image"],"free":false},
  {"id":"meta/muse-glimmer-30b","name":"Meta: Muse Glimmer 30B","contextLength":131072,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3.5-9b","name":"Qwen: Qwen3.5-9B","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"anthropic/claude-opus-5-fast","name":"Claude Opus 5 (Fast)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.2","name":"OpenAI: GPT-5.2","contextLength":400000,"inputModalities":["file","image"],"free":false},
  {"id":"deepseek/deepseek-chat","name":"DeepSeek: DeepSeek V3","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.6-27b","name":"Qwen: Qwen3.6 27B","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"meta-llama/llama-4-scout","name":"Meta: Llama 4 Scout","contextLength":10000000,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-coder-next","name":"Qwen: Qwen3 Coder Next","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-sonnet-4","name":"Anthropic: Claude Sonnet 4","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"meta-llama/llama-4-maverick","name":"Meta: Llama 4 Maverick","contextLength":1048576,"inputModalities":["image"],"free":false},
  {"id":"deepseek/deepseek-v3.2-exp","name":"DeepSeek: DeepSeek V3.2 Exp","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.1","name":"OpenAI: GPT-5.1","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4.8-fast","name":"Anthropic: Claude Opus 4.8 (Fast)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"z-ai/glm-4.7-flash","name":"Z.ai: GLM 4.7 Flash","contextLength":200000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.6-plus","name":"Qwen: Qwen3.6 Plus","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"tencent/hy3-preview","name":"Tencent: Hy3 preview","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.5-35b-a3b","name":"Qwen: Qwen3.5-35B-A3B","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"thinkingmachines/inkling","name":"Thinking Machines: Inkling","contextLength":1048576,"inputModalities":["image","audio"],"free":false},
  {"id":"mistralai/mistral-small-3.2-24b-instruct","name":"Mistral: Mistral Small 3.2 24B","contextLength":128000,"inputModalities":["image"],"free":false},
  {"id":"anthropic/claude-opus-4.5","name":"Anthropic: Claude Opus 4.5","contextLength":200000,"inputModalities":["file","image"],"free":false},
  {"id":"qwen/qwen3.6-flash","name":"Qwen: Qwen3.6 Flash","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"mistralai/mistral-small-2603","name":"Mistral: Mistral Small 4","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-vl-235b-a22b-instruct","name":"Qwen: Qwen3 VL 235B A22B Instruct","contextLength":131072,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-vl-30b-a3b-instruct","name":"Qwen: Qwen3 VL 30B A3B Instruct","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-4o","name":"OpenAI: GPT-4o","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"nvidia/nemotron-nano-9b-v2:free","name":"NVIDIA: Nemotron Nano 9B V2 (free)","contextLength":32000,"inputModalities":[],"free":true},
  {"id":"google/gemma-4-26b-a4b-it:free","name":"Google: Gemma 4 26B A4B  (free)","contextLength":262144,"inputModalities":["image"],"free":true},
  {"id":"thinkingmachines/inkling-small","name":"Thinking Machines: Inkling Small","contextLength":1048576,"inputModalities":["image","audio"],"free":false},
  {"id":"z-ai/glm-4.6","name":"Z.ai: GLM 4.6","contextLength":200000,"inputModalities":[],"free":false},
  {"id":"nvidia/nemotron-3-super-120b-a12b","name":"NVIDIA: Nemotron 3 Super","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-vl-8b-instruct","name":"Qwen: Qwen3 VL 8B Instruct","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-coder","name":"Qwen: Qwen3 Coder 480B A35B","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"mistralai/mistral-large-2512","name":"Mistral: Mistral Large 3 2512","contextLength":256000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3.5-27b","name":"Qwen: Qwen3.5-27B","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5","name":"OpenAI: GPT-5","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3.5-122b-a10b","name":"Qwen: Qwen3.5-122B-A10B","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-next-80b-a3b-instruct","name":"Qwen: Qwen3 Next 80B A3B Instruct","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"deepseek/deepseek-r1-0528","name":"DeepSeek: R1 0528","contextLength":163840,"inputModalities":[],"free":false},
  {"id":"z-ai/glm-5.2:free","name":"Z.ai: GLM 5.2 (free)","contextLength":1048576,"inputModalities":[],"free":true},
  {"id":"nvidia/nemotron-nano-12b-v2-vl:free","name":"NVIDIA: Nemotron Nano 12B 2 VL (free)","contextLength":128000,"inputModalities":["image"],"free":true},
  {"id":"liquid/lfm-2.5-2.6b:free","name":"LiquidAI: LFM2.5-2.6B (free)","contextLength":131072,"inputModalities":[],"free":true},
  {"id":"openai/gpt-oss-20b:free","name":"OpenAI: gpt-oss-20b (free)","contextLength":131072,"inputModalities":[],"free":true},
  {"id":"meituan/longcat-2.0","name":"Meituan: LongCat 2.0","contextLength":1048756,"inputModalities":[],"free":false},
  {"id":"aion-labs/aion-3.0","name":"AionLabs: Aion-3.0","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.5-plus-02-15","name":"Qwen: Qwen3.5 Plus 2026-02-15","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"deepseek/deepseek-v3.1-terminus","name":"DeepSeek: DeepSeek V3.1 Terminus","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"meta-llama/llama-3.1-70b-instruct","name":"Meta: Llama 3.1 70B Instruct","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"moonshotai/kimi-k2-0905","name":"MoonshotAI: Kimi K2 0905","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"z-ai/glm-5-turbo","name":"Z.ai: GLM 5 Turbo","contextLength":202752,"inputModalities":[],"free":false},
  {"id":"poolside/laguna-xs-2.1","name":"Poolside: Laguna XS 2.1","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4o-mini-2024-07-18","name":"OpenAI: GPT-4o-mini (2024-07-18)","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"google/gemini-3.7-flash:batch","name":"Google: Gemini 3.7 Flash (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"mistralai/mistral-medium-3-5","name":"Mistral: Mistral Medium 3.5","contextLength":262144,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3-8b","name":"Qwen: Qwen3 8B","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"z-ai/glm-4.5-air","name":"Z.ai: GLM 4.5 Air","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"mistralai/ministral-8b-2512","name":"Mistral: Ministral 3 8B 2512","contextLength":128000,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen-2.5-7b-instruct","name":"Qwen: Qwen2.5 7B Instruct","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"qwen/qwen-2.5-72b-instruct","name":"Qwen2.5 72B Instruct","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"nvidia/nemotron-3-nano-30b-a3b","name":"NVIDIA: Nemotron 3 Nano 30B A3B","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"bytedance-seed/seed-2.0-mini","name":"ByteDance Seed: Seed-2.0-Mini","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"z-ai/glm-4.5","name":"Z.ai: GLM 4.5","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"x-ai/grok-build-0.1","name":"SpaceXAI: Grok Build 0.1","contextLength":256000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3-14b","name":"Qwen: Qwen3 14B","contextLength":131702,"inputModalities":[],"free":false},
  {"id":"inclusionai/ling-2.6-1t","name":"inclusionAI: Ling-2.6-1T","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-opus-5:batch","name":"Claude Opus 5 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"inception/mercury-2","name":"Inception: Mercury 2","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"inclusionai/ring-2.6-1t","name":"inclusionAI: Ring-2.6-1T","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-3-haiku","name":"Anthropic: Claude 3 Haiku","contextLength":200000,"inputModalities":["image"],"free":false},
  {"id":"moonshotai/kimi-k2","name":"MoonshotAI: Kimi K2 0711","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"mistralai/ministral-14b-2512","name":"Mistral: Ministral 3 14B 2512","contextLength":128000,"inputModalities":["image"],"free":false},
  {"id":"amazon/nova-lite-v1","name":"Amazon: Nova Lite 1.0","contextLength":300000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-4o-2024-11-20","name":"OpenAI: GPT-4o (2024-11-20)","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"mistralai/mistral-medium-3.1","name":"Mistral: Mistral Medium 3.1","contextLength":131072,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3-max","name":"Qwen: Qwen3 Max","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-235b-a22b-thinking-2507","name":"Qwen: Qwen3 235B A22B Thinking 2507","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"aion-labs/aion-2.0","name":"AionLabs: Aion-2.0","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"deepseek/deepseek-r1","name":"DeepSeek: R1","contextLength":163840,"inputModalities":[],"free":false},
  {"id":"aion-labs/aion-3.0-mini","name":"AionLabs: Aion-3.0-Mini","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"moonshotai/kimi-k2-thinking","name":"MoonshotAI: Kimi K2 Thinking","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-coder-flash","name":"Qwen: Qwen3 Coder Flash","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"stepfun/step-3.5-flash","name":"StepFun: Step 3.5 Flash","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3-235b-a22b","name":"Qwen: Qwen3 235B A22B","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"mistralai/ministral-3b-2512","name":"Mistral: Ministral 3 3B 2512","contextLength":128000,"inputModalities":["image"],"free":false},
  {"id":"bytedance-seed/seed-1.6-flash","name":"ByteDance Seed: Seed 1.6 Flash","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"google/gemini-3.1-pro-preview-customtools","name":"Google: Gemini 3.1 Pro Preview Custom Tools","contextLength":1048756,"inputModalities":["audio","image","file"],"free":false},
  {"id":"kwaipilot/kat-coder-air-v2.5","name":"Kwaipilot: KAT-Coder-Air V2.5","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"ibm-granite/granite-4.1-8b","name":"IBM: Granite 4.1 8B","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.5-plus-20260420","name":"Qwen: Qwen3.5 Plus 2026-04-20","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"google/gemma-4-31b-it:free","name":"Google: Gemma 4 31B (free)","contextLength":262144,"inputModalities":["image"],"free":true},
  {"id":"openai/gpt-5.1-codex-mini","name":"OpenAI: GPT-5.1-Codex-Mini","contextLength":400000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-4o-2024-08-06","name":"OpenAI: GPT-4o (2024-08-06)","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"sakana/fugu-ultra","name":"Sakana: Fugu Ultra","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"openai/o4-mini","name":"OpenAI: o4 Mini","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3-30b-a3b","name":"Qwen: Qwen3 30B A3B","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"nex-agi/nex-n2-pro","name":"Nex AGI: Nex-N2-Pro","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-coder-plus","name":"Qwen: Qwen3 Coder Plus","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.1-codex","name":"OpenAI: GPT-5.1-Codex","contextLength":400000,"inputModalities":["image"],"free":false},
  {"id":"minimax/minimax-m2.1","name":"MiniMax: MiniMax M2.1","contextLength":204800,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5-mini:batch","name":"OpenAI: GPT-5 Mini (batch)","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"z-ai/glm-4.6v","name":"Z.ai: GLM 4.6V","contextLength":131072,"inputModalities":["image"],"free":false},
  {"id":"kwaipilot/kat-coder-pro-v2.5","name":"Kwaipilot: KAT-Coder-Pro V2.5","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.2-codex","name":"OpenAI: GPT-5.2-Codex","contextLength":400000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-chat-latest","name":"OpenAI: GPT Chat Latest","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"bytedance-seed/seed-2.0-lite","name":"ByteDance Seed: Seed-2.0-Lite","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"google/gemini-3-pro-image","name":"Google: Nano Banana Pro (Gemini 3 Pro Image)","contextLength":65536,"inputModalities":["image"],"free":false},
  {"id":"google/gemini-2.5-flash:batch","name":"Google: Gemini 2.5 Flash (batch)","contextLength":1048576,"inputModalities":["file","image","audio"],"free":false},
  {"id":"google/gemini-3-flash-preview:batch","name":"Google: Gemini 3 Flash Preview (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"qwen/qwen-plus","name":"Qwen: Qwen-Plus","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"minimax/minimax-m2","name":"MiniMax: MiniMax M2","contextLength":204800,"inputModalities":[],"free":false},
  {"id":"deepseek/deepseek-v4-flash-vision-exp","name":"DeepSeek: DeepSeek V4 Flash Vision Exp","contextLength":1048576,"inputModalities":["image"],"free":false},
  {"id":"arcee-ai/trinity-large-thinking","name":"Arcee AI: Trinity Large Thinking","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.6-luna:batch","name":"OpenAI: GPT-5.6 Luna (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-3.5-turbo:batch","name":"OpenAI: GPT-3.5 Turbo (batch)","contextLength":16385,"inputModalities":[],"free":false},
  {"id":"openai/o3","name":"OpenAI: o3","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"kwaipilot/kat-coder-pro-v2","name":"Kwaipilot: KAT-Coder-Pro V2","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"bytedance-seed/seed-2-1-turbo","name":"ByteDance Seed: Seed 2.1 Turbo","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"mistralai/codestral-2508","name":"Mistral: Codestral 2508","contextLength":256000,"inputModalities":["file"],"free":false},
  {"id":"anthropic/claude-opus-4.1","name":"Anthropic: Claude Opus 4.1","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"mistralai/mistral-large","name":"Mistral Large","contextLength":128000,"inputModalities":["file"],"free":false},
  {"id":"amazon/nova-2-lite-v1","name":"Amazon: Nova 2 Lite","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4","name":"Anthropic: Claude Opus 4","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"bytedance-seed/seed-2.0-code","name":"ByteDance Seed: Seed-2.0-Code","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-max-thinking","name":"Qwen: Qwen3 Max Thinking","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"thedrummer/unslopnemo-12b","name":"TheDrummer: UnslopNemo 12B","contextLength":32000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4o-mini:batch","name":"OpenAI: GPT-4o-mini (batch)","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"minimax/minimax-m3:batch","name":"MiniMax: MiniMax M3 (batch)","contextLength":1048576,"inputModalities":["image"],"free":false},
  {"id":"anthropic/claude-haiku-4.5:batch","name":"Anthropic: Claude Haiku 4.5 (batch)","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-3.5-turbo","name":"OpenAI: GPT-3.5 Turbo","contextLength":16385,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4o:batch","name":"OpenAI: GPT-4o (batch)","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3-next-80b-a3b-thinking","name":"Qwen: Qwen3 Next 80B A3B Thinking","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"google/gemini-2.5-flash-lite:batch","name":"Google: Gemini 2.5 Flash Lite (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"qwen/qwen-plus-2025-07-28","name":"Qwen: Qwen Plus 0728","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"qwen/qwen3.6-max-preview","name":"Qwen: Qwen3.6 Max Preview","contextLength":262144,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-fable-5:batch","name":"Anthropic: Claude Fable 5 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.1-codex-max","name":"OpenAI: GPT-5.1-Codex-Max","contextLength":400000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.6-luna-pro:batch","name":"OpenAI: GPT-5.6 Luna Pro (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"mistralai/mistral-medium-3","name":"Mistral: Mistral Medium 3","contextLength":131072,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.5-pro","name":"OpenAI: GPT-5.5 Pro","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"amazon/nova-premier-v1","name":"Amazon: Nova Premier 1.0","contextLength":1000000,"inputModalities":["image"],"free":false},
  {"id":"google/gemini-3.1-flash-lite:batch","name":"Google: Gemini 3.1 Flash Lite (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"moonshotai/kimi-k2.7-code:batch","name":"MoonshotAI: Kimi K2.7 Code (batch)","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-audio-mini","name":"OpenAI: GPT Audio Mini","contextLength":128000,"inputModalities":["audio"],"free":false},
  {"id":"anthropic/claude-sonnet-5:batch","name":"Anthropic: Claude Sonnet 5 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen3-vl-235b-a22b-thinking","name":"Qwen: Qwen3 VL 235B A22B Thinking","contextLength":131072,"inputModalities":["image"],"free":false},
  {"id":"amazon/nova-pro-v1","name":"Amazon: Nova Pro 1.0","contextLength":300000,"inputModalities":["image"],"free":false},
  {"id":"qwen/qwen3-30b-a3b-thinking-2507","name":"Qwen: Qwen3 30B A3B Thinking 2507","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.6-sol:batch","name":"OpenAI: GPT-5.6 Sol (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"qwen/qwen3-vl-8b-thinking","name":"Qwen: Qwen3 VL 8B Thinking","contextLength":256000,"inputModalities":["image"],"free":false},
  {"id":"google/gemini-3.6-flash:batch","name":"Google: Gemini 3.6 Flash (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"openai/gpt-5-nano:batch","name":"OpenAI: GPT-5 Nano (batch)","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"z-ai/glm-4.5v","name":"Z.ai: GLM 4.5V","contextLength":65536,"inputModalities":["image"],"free":false},
  {"id":"sao10k/l3.1-euryale-70b","name":"Sao10K: Llama 3.1 Euryale 70B v2.2","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"openai/o3-mini","name":"OpenAI: o3 Mini","contextLength":200000,"inputModalities":["file"],"free":false},
  {"id":"mistralai/mistral-large-2407","name":"Mistral Large 2407","contextLength":128000,"inputModalities":["file"],"free":false},
  {"id":"google/gemini-3.5-flash-lite:batch","name":"Google: Gemini 3.5 Flash Lite (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"upstage/solar-pro-3","name":"Upstage: Solar Pro 3","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4o-2024-05-13","name":"OpenAI: GPT-4o (2024-05-13)","contextLength":128000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.6-sol-pro:batch","name":"OpenAI: GPT-5.6 Sol Pro (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"cohere/command-r-plus-08-2024","name":"Cohere: Command R+ (08-2024)","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"mistralai/mixtral-8x22b-instruct","name":"Mistral: Mixtral 8x22B Instruct","contextLength":65536,"inputModalities":["file"],"free":false},
  {"id":"cohere/command-r-08-2024","name":"Cohere: Command R (08-2024)","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"mistralai/voxtral-small-24b-2507","name":"Mistral: Voxtral Small 24B 2507","contextLength":32000,"inputModalities":["audio","file"],"free":false},
  {"id":"bytedance-seed/seed-1.6","name":"ByteDance Seed: Seed 1.6","contextLength":262144,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.5:batch","name":"OpenAI: GPT-5.5 (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-4-turbo","name":"OpenAI: GPT-4 Turbo","contextLength":128000,"inputModalities":["image"],"free":false},
  {"id":"minimax/minimax-m1","name":"MiniMax: MiniMax M1","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"google/gemini-3.1-pro-preview:batch","name":"Google: Gemini 3.1 Pro Preview (batch)","contextLength":1048576,"inputModalities":["audio","file","image"],"free":false},
  {"id":"openai/o4-mini-high","name":"OpenAI: o4 Mini High","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"qwen/qwen-plus-2025-07-28:thinking","name":"Qwen: Qwen Plus 0728 (thinking)","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"anthropic/claude-sonnet-4.6:batch","name":"Anthropic: Claude Sonnet 4.6 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"mistralai/mistral-saba","name":"Mistral: Saba","contextLength":32000,"inputModalities":["file"],"free":false},
  {"id":"anthropic/claude-sonnet-4.5:batch","name":"Anthropic: Claude Sonnet 4.5 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-4","name":"OpenAI: GPT-4","contextLength":8191,"inputModalities":[],"free":false},
  {"id":"openai/o1","name":"OpenAI: o1","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.4:batch","name":"OpenAI: GPT-5.4 (batch)","contextLength":1050000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.4-pro","name":"OpenAI: GPT-5.4 Pro","contextLength":1050000,"inputModalities":["image","file"],"free":false},
  {"id":"sakana/sakana-namazu","name":"Sakana: Sakana Namazu","contextLength":262144,"inputModalities":["image","file"],"free":false},
  {"id":"rekaai/reka-edge","name":"Reka Edge","contextLength":16384,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5.6-terra:batch","name":"OpenAI: GPT-5.6 Terra (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"z-ai/glm-5.2:batch","name":"Z.ai: GLM 5.2 (batch)","contextLength":1048576,"inputModalities":[],"free":false},
  {"id":"relace/relace-search","name":"Relace: Relace Search","contextLength":256000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-audio","name":"OpenAI: GPT Audio","contextLength":128000,"inputModalities":["audio"],"free":false},
  {"id":"google/gemini-2.5-pro:batch","name":"Google: Gemini 2.5 Pro (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"openai/gpt-4.1-mini:batch","name":"OpenAI: GPT-4.1 Mini (batch)","contextLength":1047576,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.2-pro","name":"OpenAI: GPT-5.2 Pro","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"google/gemini-3.5-flash:batch","name":"Google: Gemini 3.5 Flash (batch)","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"nvidia/nemotron-3-ultra-550b-a55b:batch","name":"NVIDIA: Nemotron 3 Ultra (batch)","contextLength":1000000,"inputModalities":[],"free":false},
  {"id":"openai/o3-mini-high","name":"OpenAI: o3 Mini High","contextLength":200000,"inputModalities":["file"],"free":false},
  {"id":"openai/o3-pro","name":"OpenAI: o3 Pro","contextLength":200000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-3.5-turbo-0613","name":"OpenAI: GPT-3.5 Turbo (older v0613)","contextLength":4095,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.4-nano:batch","name":"OpenAI: GPT-5.4 Nano (batch)","contextLength":400000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-5-pro","name":"OpenAI: GPT-5 Pro","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-3.5-turbo-16k","name":"OpenAI: GPT-3.5 Turbo 16k","contextLength":16385,"inputModalities":[],"free":false},
  {"id":"openai/gpt-5.4-mini:batch","name":"OpenAI: GPT-5.4 Mini (batch)","contextLength":400000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-4.1:batch","name":"OpenAI: GPT-4.1 (batch)","contextLength":1047576,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4.7:batch","name":"Anthropic: Claude Opus 4.7 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5:batch","name":"OpenAI: GPT-5 (batch)","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.2:batch","name":"OpenAI: GPT-5.2 (batch)","contextLength":400000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-5.6-terra-pro:batch","name":"OpenAI: GPT-5.6 Terra Pro (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/o4-mini:batch","name":"OpenAI: o4 Mini (batch)","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"thinkingmachines/inkling:batch","name":"Thinking Machines: Inkling (batch)","contextLength":1048576,"inputModalities":["image","audio"],"free":false},
  {"id":"anthropic/claude-opus-4.6:batch","name":"Anthropic: Claude Opus 4.6 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4.8:batch","name":"Anthropic: Claude Opus 4.8 (batch)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.2-chat","name":"OpenAI: GPT-5.2 Chat","contextLength":128000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/gpt-4.1-nano:batch","name":"OpenAI: GPT-4.1 Nano (batch)","contextLength":1047576,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.1:batch","name":"OpenAI: GPT-5.1 (batch)","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4.5:batch","name":"Anthropic: Claude Opus 4.5 (batch)","contextLength":200000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/o3-mini:batch","name":"OpenAI: o3 Mini (batch)","contextLength":200000,"inputModalities":["file"],"free":false},
  {"id":"openai/o3:batch","name":"OpenAI: o3 (batch)","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/o1:batch","name":"OpenAI: o1 (batch)","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4.1:batch","name":"Anthropic: Claude Opus 4.1 (batch)","contextLength":200000,"inputModalities":["image","file"],"free":false},
  {"id":"anthropic/claude-opus-4.7-fast","name":"Anthropic: Claude Opus 4.7 (Fast)","contextLength":1000000,"inputModalities":["image","file"],"free":false},
  {"id":"arcee-ai/virtuoso-large","name":"Arcee AI: Virtuoso Large","contextLength":131072,"inputModalities":[],"free":false},
  {"id":"google/gemini-2.5-pro-preview-05-06","name":"Google: Gemini 2.5 Pro Preview 05-06","contextLength":1048576,"inputModalities":["image","file","audio"],"free":false},
  {"id":"google/gemini-2.5-pro-preview","name":"Google: Gemini 2.5 Pro Preview 06-05","contextLength":1048576,"inputModalities":["file","image","audio"],"free":false},
  {"id":"openai/gpt-4-turbo-preview","name":"OpenAI: GPT-4 Turbo Preview","contextLength":128000,"inputModalities":[],"free":false},
  {"id":"openai/gpt-4-turbo:batch","name":"OpenAI: GPT-4 Turbo (batch)","contextLength":128000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5-codex:batch","name":"OpenAI: GPT-5 Codex (batch)","contextLength":400000,"inputModalities":["image"],"free":false},
  {"id":"openai/gpt-5-pro:batch","name":"OpenAI: GPT-5 Pro (batch)","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.2-pro:batch","name":"OpenAI: GPT-5.2 Pro (batch)","contextLength":400000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.4-pro:batch","name":"OpenAI: GPT-5.4 Pro (batch)","contextLength":1050000,"inputModalities":["image","file"],"free":false},
  {"id":"openai/gpt-5.5-pro:batch","name":"OpenAI: GPT-5.5 Pro (batch)","contextLength":1050000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/o3-mini-high:batch","name":"OpenAI: o3 Mini High (batch)","contextLength":200000,"inputModalities":["file"],"free":false},
  {"id":"openai/o3-pro:batch","name":"OpenAI: o3 Pro (batch)","contextLength":200000,"inputModalities":["file","image"],"free":false},
  {"id":"openai/o4-mini-high:batch","name":"OpenAI: o4 Mini High (batch)","contextLength":200000,"inputModalities":["image","file"],"free":false},
];
