/// Layout-independent input accepted by the subagent manager and selected-child
/// composer after UI has translated terminal encodings.
pub const Action = enum {
    up,
    down,
    left,
    right,
    page_up,
    page_down,
    enter,
    focus_next,
    activity,
    notifications,
    archived,
    next_page,
    previous_page,
    escape,
    toggle,
    ctrl_c,
    home,
    end,
    word_left,
    word_right,
    delete_backward,
    delete_next,
    delete_word_left,
    delete_word_right,
    delete_to_line_start,
    delete_to_line_end,
    clear_line,
    insert_newline,
};

/// Effect requested by the subagent state transition. The Core app runtime
/// performs the effect after the UI-owned state machine returns this value.
pub const Command = enum {
    none,
    redraw,
    page_changed,
    exit_app,
    close_manager,
    acknowledge,
    child_changed,
    load_older_history,
    refresh_newest_history,
    submit_child_message,
    load_attach_candidates,
    load_more_attach_candidates,
    submit_manager_mutation,
    resolve_child_approval,
    open_terminal,
};
