import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { CatalogCache, fetchOpenRouterCatalog, type CatalogModel } from "../main/catalog";
import { freeModels, freeRouterChain, thinkingStops, FREE_ROUTER_MODELS } from "../shared/settings";

const model = (id: string, free = true): CatalogModel =>
  ({ id, name: id, contextLength: 1024, inputModalities: [], free });

test("the catalog caches to disk, reports what changed, and survives a dead fetch", async () => {
  const dir = await mkdtemp(path.join(tmpdir(), "emma-catalog-"));
  try {
    // A first launch has no cache, so the bundled seed is what the models page shows.
    const seeded = new CatalogCache(dir);
    const offline = await seeded.refresh(() => Promise.reject(new Error("no network")));
    assert.ok(offline.stale);
    assert.equal(offline.error, "no network");
    assert.ok(offline.models.length > 0, "the bundled seed stands in before any fetch lands");
    assert.ok(offline.models.some((entry) => !entry.free), "the seed carries paid models too");

    // The seed is generated by the same parse as a live fetch, so it carries every field
    // that fetch produces. When it did not, the slider had no stops on a first launch and
    // every turn ran at the model's default.
    const thinker = offline.models.find((entry) => entry.reasoningEfforts?.length);
    assert.ok(thinker, "the seed publishes reasoning efforts");
    assert.ok(thinkingStops(thinker).length > 1, "so a reasoning model has slider stops before any fetch lands");
    assert.equal(thinkingStops(thinker)[0], "", "starting, as always, on the model's own default");
    // A model that publishes nothing still gets no knob to move.
    const quiet = offline.models.find((entry) => !entry.reasoningEfforts?.length);
    assert.ok(quiet, "the seed carries models that do not think either");
    assert.deepEqual(thinkingStops(quiet), []);
    assert.ok(offline.models.some((entry) => entry.promptMicroUsdPerMtok), "and the prices the models page quotes");

    const first = await seeded.refresh(() => Promise.resolve({ models: [model("a/one"), model("b/two", false)] }));
    assert.equal(first.stale, false);
    assert.deepEqual(first.models.map((entry) => entry.id), ["a/one", "b/two"]);
    assert.equal(first.models[1].free, false);

    // A reload that lands on the same list has to say so rather than look inert.
    const again = await seeded.refresh(() => Promise.resolve({ models: [model("a/one"), model("b/two", false)] }));
    assert.deepEqual(again.added, []);
    assert.deepEqual(again.removed, []);

    const changed = await seeded.refresh(() => Promise.resolve({ models: [model("a/one"), model("c/three")] }));
    assert.deepEqual(changed.added, ["c/three"]);
    assert.deepEqual(changed.removed, ["b/two"]);

    // A fresh process reads the last good fetch off disk, not the seed.
    const reopened = new CatalogCache(dir);
    const cached = await reopened.refresh(() => Promise.reject(new Error("still offline")));
    assert.ok(cached.stale);
    assert.deepEqual(cached.models.map((entry) => entry.id), ["a/one", "c/three"]);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("free-only routing keeps the catalog's free models and whatever is already selected", () => {
  const entries = [
    { key: "fallback" },
    { key: "local:one" },
    { key: "openrouter:a/one", free: true },
    { key: "openrouter:b/two", free: false },
  ];
  const keys = (active: string) => freeModels(entries, active).map((entry) => entry.key);
  // A local profile costs nothing to run and is still not a free catalog model.
  assert.deepEqual(keys(""), ["openrouter:a/one"]);
  // The model in use never disappears from its own picker, free or not.
  assert.deepEqual(keys("openrouter:b/two"), ["openrouter:a/one", "openrouter:b/two"]);
  assert.deepEqual(keys("fallback"), ["fallback", "openrouter:a/one"]);
});

test("the free router sends the whole chain, in order, minus what the catalog has dropped", () => {
  // Nothing catalogued to check against — offline, or a cache that has never landed —
  // is the full chain rather than an empty one: OpenRouter is the judge of what answers.
  assert.equal(freeRouterChain().split(",").length, FREE_ROUTER_MODELS.length);
  assert.equal(freeRouterChain(), FREE_ROUTER_MODELS.join(","));
  const listed = [FREE_ROUTER_MODELS[2], FREE_ROUTER_MODELS[0], "someone/else"];
  // The catalog says which still exist; the chain's own order says which is tried first.
  assert.equal(freeRouterChain(listed), `${FREE_ROUTER_MODELS[0]},${FREE_ROUTER_MODELS[2]}`);
  // A catalog with none of them left is a stale list here, not a request with no model on it.
  assert.equal(freeRouterChain(["someone/else"]), FREE_ROUTER_MODELS.join(","));
});

test("the OpenRouter listing is parsed, priced, and filtered to models Emma can actually use", async () => {
  const row = (over: Record<string, unknown> = {}) => ({
    id: "vendor/model",
    name: "Vendor Model",
    context_length: 8192,
    supported_parameters: ["tools"],
    pricing: { prompt: "0.000001", completion: "0.000002" },
    architecture: { input_modalities: ["text", "image"] },
    ...over,
  });
  const served = (data: unknown[]) => {
    const original = globalThis.fetch;
    globalThis.fetch = (async () => new Response(JSON.stringify({ data }), {
      status: 200, headers: { "content-type": "application/json" },
    })) as typeof fetch;
    return () => { globalThis.fetch = original; };
  };

  let restore = served([
    row(),
    // Dropped: Emma advertises tools every turn, so a model without them fails on first use.
    row({ id: "vendor/no-tools", supported_parameters: ["temperature"] }),
    // Dropped: one vendor's bad row, not a corrupt listing.
    row({ id: "vendor/no-window", context_length: 0 }),
    row({ id: "not-a-path", name: "Malformed Id" }),
    // Deduped against the first row.
    row({ name: "Duplicate" }),
    row({
      id: "vendor/free-thinker",
      name: "Free Thinker",
      pricing: { prompt: "0", completion: "0" },
      reasoning: { supported_efforts: ["low", "max"], mandatory: true },
    }),
    row({
      id: "vendor/default-stops",
      name: "Default Stops",
      supported_parameters: ["tools", "reasoning_effort"],
    }),
  ]);
  try {
    const { models } = await fetchOpenRouterCatalog();
    assert.deepEqual(models.map((entry) => entry.id), ["vendor/default-stops", "vendor/free-thinker", "vendor/model"]);

    const paid = models.find((entry) => entry.id === "vendor/model")!;
    assert.equal(paid.free, false);
    // Dollars per token to micro-dollars per million tokens: the same number times 1e12.
    assert.equal(paid.promptMicroUsdPerMtok, 1_000_000);
    assert.equal(paid.completionMicroUsdPerMtok, 2_000_000);
    // A listing quirk should not promise vision: only the modalities Emma knows survive.
    assert.deepEqual(paid.inputModalities, ["image"]);
    assert.deepEqual(paid.reasoningEfforts, []);

    const thinker = models.find((entry) => entry.id === "vendor/free-thinker")!;
    assert.equal(thinker.free, true);
    // Published efforts come back weakest-first, whatever order the vendor listed them in.
    assert.deepEqual(thinker.reasoningEfforts, ["low", "max"]);
    assert.equal(thinker.reasoningMandatory, true);

    // `reasoning_effort` with no published list gets OpenRouter's own three stops.
    assert.deepEqual(models.find((entry) => entry.id === "vendor/default-stops")!.reasoningEfforts, ["low", "medium", "high"]);
  } finally { restore(); }

  // A listing with nothing usable in it is an error, not an empty picker.
  restore = served([row({ supported_parameters: ["temperature"] })]);
  try {
    await assert.rejects(fetchOpenRouterCatalog(), /no models Emma can use/);
  } finally { restore(); }
});
